GET http://localhost:4000/blogposts

###
GET http://localhost:4000/blogposts/63c5f7d543ff91545ae62f4e

###
POST http://localhost:4000/blogposts
Content-Type: application/json

{
    "author": "Unknown",
    "title": "Test Post Title 3",
    "content": "Test Post Content 3"
}

###
DELETE http://localhost:4000/blogposts/63c32f2a00d8d46fa6eddb1f

###
PATCH http://localhost:4000/blogposts/63c32f4f00d8d46fa6eddb29
Content-Type: application/json

{
    "title": "New Title 3 - 1"
}

###
GET http://localhost:4000/blogusers

###
GET http://localhost:4000/blogusers/63c5a8eabd264d787a74d31c

###
POST http://localhost:4000/blogusers/register
Content-Type: application/json

{
    "firstName": "Danss4",
    "lastName": "Karrels",
    "userName": "danny23",
    "pwd": "Abc12345!!"
}

###
PATCH http://localhost:4000/blogusers/63c478d35af1b6419558aead
Content-Type: application/json

{
    "hashedPassword": "Abc12345678!!"
}

###
DELETE http://localhost:4000/blogusers/63c5e425909bffd8daf5d771

###
POST http://localhost:4000/blogusers/authenticate
Content-Type: application/json

{
    "userName": "danny2",
    "pwd": "Abc12345!!"
}

###
GET http://localhost:4000/blogusers/refresh

###
GET http://localhost:4000/blogusers/logout